export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN2_SUCCESS = "LOGIN2_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const SET_OTP_MESSAGE = "SET_OTP_MESSAGE";
export const CLEAR_OTP_MESSAGE = "CLEAR_OTP_MESSAGE";
export const SET_SIGNUP_MESSAGE = "SET_SIGNUP_MESSAGE";
export const CLEAR_SIGNUP_MESSAGE = "CLEAR_SIGNUP_MESSAGE";

export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

